name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies for Livestream
      run: npm ci
      working-directory: LiveNex-user-server/live-stream

    - name: Build Livestream
      run: npm run build
      working-directory: LiveNex-user-server/live-stream

    - name: Install Dependencies for User
      run: npm ci
      working-directory: LiveNex-user-server/user

    - name: Build User
      run: npm run build
      working-directory: LiveNex-user-server/user
